CREATE OR REPLACE TYPE FS_AUWEB_US.MO_TOCROMO IS

OBJECT (
		ROLL_ROLL NUMBER(22),
		ROLL_RLDN VARCHAR2(50),
		ROLL_FCMO DATE,
		MODU_MODU NUMBER(22),
		MODU_NAME VARCHAR2(50),
		MODU_DESC VARCHAR2(50),
		ROMO_ROMO NUMBER(22),
		ROMO_MODU NUMBER(22),
		ROMO_ROLL NUMBER(22)
		);
		
/
