create or replace TYPE FS_AUWEB_US.US_TOWPURS IS

OBJECT (
		USER_ALAS VARCHAR2(40),
		PSNA_NOBE VARCHAR2(70),
		PSNA_APDO VARCHAR2(70),
		PSNA_DIRN VARCHAR2(50),
		PSNA_TLFN VARCHAR2(50),
		PSNA_EMAL VARCHAR2(50),
		PSNA_PAIS VARCHAR2(50),
		PSNA_NRID VARCHAR2(50),
		ROLL_RLDN VARCHAR2(50)
		);
		
/
