CREATE OR REPLACE TYPE FS_AUWEB_US.US_TOCPURS IS

OBJECT (
		USER_USER NUMBER(22),
		USER_ALAS VARCHAR2(40),
		USER_PSWD VARCHAR2(40),
		PSNA_PSNA NUMBER(22),
		PSNA_NOBE VARCHAR2(70),
		PSNA_APDO VARCHAR2(70),
		PSNA_DIRN VARCHAR2(50),
		PSNA_TLFN VARCHAR2(50),
		PSNA_EMAL VARCHAR2(50),
		PSNA_PAIS VARCHAR2(50),
		PSNA_NRID VARCHAR2(50),
		ROLL_ROLL NUMBER(22),
		ROLL_RLDN VARCHAR2(50),
		ROLL_FCMO DATE,
		PUSR_PUSR NUMBER(22),
		PUSR_USER NUMBER(22),
		PUSR_ROLL NUMBER(22),
		PURS_PSNA NUMBER(22)
		);
		
/
