/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 08-may.-2018 12:53:36 p. m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "MO_TMODU" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "MO_TROMO" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_AUWEB_US"."US_TPSNE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "US_TPUSR" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "US_TRLNE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_AUWEB_US"."US_TUSNE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  
/

/* Create Tables */

CREATE TABLE  "MO_TMODU"
(
	"MODU_MODU" NUMBER(22) NOT NULL,    -- Identificador  unico del modulo
	"MODU_NAME" VARCHAR2(50) NULL,
	"MODU_DESC" VARCHAR2(50) NULL
)
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	BUFFER_POOL	DEFAULT
	)
LOGGING
DISABLE
NOCACHE
MONITORING
;

CREATE TABLE  "MO_TROMO"
(
	"ROMO_ROMO" NUMBER(22) NOT NULL,    -- Identificador unico modulos con rol
	"MODU_MODU" NUMBER(22) NULL,
	"RLNE_RLNE" NUMBER(22) NULL
)
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	BUFFER_POOL	DEFAULT
	)
LOGGING
DISABLE
NOCACHE
MONITORING
;

CREATE TABLE  "FS_AUWEB_US"."US_TPSNE"
(
	"PSNE_PSNE" NUMBER(22) NOT NULL,    -- Identificador  unico del usuario en el negocio
	"PSNE_NOBE" VARCHAR2(70) NOT NULL,    -- Nombres del usuario en el negocio
	"PSNE_APDO" VARCHAR2(70) NULL,    -- Apellidos del usuario en el negocio
	"PSNE_DIRN" VARCHAR2(50) NULL,    -- Direccion  del usuario en el negocio
	"PSNE_TLFN" VARCHAR2(50) NULL,    -- telefono del usuario en el negocio
	"PSNE_EMAL" VARCHAR2(50) NULL,    -- Email  del usuario en el negocio
	"PSNE_PAIS" VARCHAR2(50) NULL,    -- Pais  del usuario en el negocio
	"PSNE_NRID" VARCHAR2(50) NULL    -- Numero de indentificacion del usuario
)
TABLESPACE	TS_AUWEB
;

CREATE TABLE  "US_TPUSR"
(
	"PUSR_PUSR" NUMBER(22) NOT NULL,    -- Identificador  unico del usuario rol persona
	"USNE_USNE" NUMBER(22) NULL,
	"RLNE_RLNE" NUMBER(22) NULL,
	"PSNE_PSNE" NUMBER(22) NULL
)
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	BUFFER_POOL	DEFAULT
	)
LOGGING
DISABLE
NOCACHE
MONITORING
;

CREATE TABLE  "US_TRLNE"
(
	"RLNE_RLNE" NUMBER(22) NOT NULL,    -- Codigo unico tipo Rol asignado por el sistema
	"RLNE_RLDN" VARCHAR2(50) NOT NULL,    -- Descripcion del rol asignado por el sistema
	"RLNE_FCMO" DATE NOT NULL    -- Fecha de Modificacion del tipo rol
)
;

CREATE TABLE  "FS_AUWEB_US"."US_TUSNE"
(
	"USNE_USNE" NUMBER(22) NOT NULL,    -- Identificador  unico del usuario en el negocio
	"USNE_ALAS" VARCHAR2(40) NOT NULL,    -- Nombres del usuario en el negocio
	"USNE_PSWD" VARCHAR2(40) NOT NULL    -- password del usuario en el negocio
)
TABLESPACE	TS_AUWEB
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  "MO_TMODU" IS 'Tabla que contendra los modulos del sistema'
;

COMMENT ON COLUMN  "MO_TMODU"."MODU_MODU" IS 'Identificador  unico del modulo'
;

COMMENT ON TABLE  "MO_TROMO" IS 'Tabla que contendra la realcion entre rol de usuario y columnas'
;

COMMENT ON COLUMN  "MO_TROMO"."ROMO_ROMO" IS 'Identificador unico modulos con rol'
;

COMMENT ON TABLE  "FS_AUWEB_US"."US_TPSNE" IS 'Tabla que contendra las personas del negocio respectivo '
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TPSNE"."PSNE_PSNE" IS 'Identificador  unico del usuario en el negocio'
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TPSNE"."PSNE_NOBE" IS 'Nombres del usuario en el negocio'
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TPSNE"."PSNE_APDO" IS 'Apellidos del usuario en el negocio'
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TPSNE"."PSNE_DIRN" IS 'Direccion  del usuario en el negocio'
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TPSNE"."PSNE_TLFN" IS 'telefono del usuario en el negocio'
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TPSNE"."PSNE_EMAL" IS 'Email  del usuario en el negocio'
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TPSNE"."PSNE_PAIS" IS 'Pais  del usuario en el negocio'
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TPSNE"."PSNE_NRID" IS 'Numero de indentificacion del usuario'
;

COMMENT ON TABLE  "US_TPUSR" IS 'Tabla que contendra la persona el usuario y su rol'
;

COMMENT ON COLUMN  "US_TPUSR"."PUSR_PUSR" IS 'Identificador  unico del usuario rol persona'
;

COMMENT ON TABLE  "US_TRLNE" IS 'Tipo de Rol usuarios AUWEB'
;

COMMENT ON COLUMN  "US_TRLNE"."RLNE_RLNE" IS 'Codigo unico tipo Rol asignado por el sistema'
;

COMMENT ON COLUMN  "US_TRLNE"."RLNE_RLDN" IS 'Descripcion del rol asignado por el sistema'
;

COMMENT ON COLUMN  "US_TRLNE"."RLNE_FCMO" IS 'Fecha de Modificacion del tipo rol'
;

COMMENT ON TABLE  "FS_AUWEB_US"."US_TUSNE" IS 'Tabla que contendra los usuarios del negocio respectivo de empresa '
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TUSNE"."USNE_USNE" IS 'Identificador  unico del usuario en el negocio'
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TUSNE"."USNE_ALAS" IS 'Nombres del usuario en el negocio'
;

COMMENT ON COLUMN  "FS_AUWEB_US"."US_TUSNE"."USNE_PSWD" IS 'password del usuario en el negocio'
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "MO_TMODU" 
 ADD CONSTRAINT "PK_MODU"
	PRIMARY KEY ("MODU_MODU") 
 USING INDEX
;

CREATE INDEX "PK_MOTMODU"   
 ON  "MO_TMODU" ("MODU_MODU") 
TABLESPACE	TS_IAUWEB
;

ALTER TABLE  "MO_TROMO" 
 ADD CONSTRAINT "PK_ROMO"
	PRIMARY KEY ("ROMO_ROMO") 
 USING INDEX
;

CREATE INDEX "IXFK_MO_TROMO_MO_TMODU"   
 ON  "MO_TROMO" ("MODU_MODU") 
;

CREATE INDEX "IXFK_MO_TROMO_US_TRLNE"   
 ON  "MO_TROMO" ("RLNE_RLNE") 
;

CREATE INDEX "PK_MOTROMO"   
 ON  "MO_TROMO" ("ROMO_ROMO") 
TABLESPACE	TS_IAUWEB
;

ALTER TABLE  "FS_AUWEB_US"."US_TPSNE" 
 ADD CONSTRAINT "PK_PSNE"
	PRIMARY KEY ("PSNE_PSNE") 
 USING INDEX
;

CREATE INDEX "PK_USTPSNE"   
 ON  "FS_AUWEB_US"."US_TPSNE" ("PSNE_PSNE") 
TABLESPACE	TS_IAUWEB
;

ALTER TABLE  "US_TPUSR" 
 ADD CONSTRAINT "PK_PUSR"
	PRIMARY KEY ("PUSR_PUSR") 
 USING INDEX
;

CREATE INDEX "IXFK_US_TPUSR_US_TPSNE"   
 ON  "US_TPUSR" ("PSNE_PSNE") 
;

CREATE INDEX "IXFK_US_TPUSR_US_TRLNE"   
 ON  "US_TPUSR" ("RLNE_RLNE") 
;

CREATE INDEX "IXFK_US_TPUSR_US_TUSNE"   
 ON  "US_TPUSR" ("USNE_USNE") 
;

CREATE INDEX "PK_USTPUSR"   
 ON  "US_TPUSR" ("PUSR_PUSR") 
TABLESPACE	TS_IAUWEB
;

ALTER TABLE  "US_TRLNE" 
 ADD CONSTRAINT "PK_TPRL"
	PRIMARY KEY ("RLNE_RLNE") 
 USING INDEX
;

CREATE INDEX "PK_USTPRL"   
 ON  "US_TRLNE" ("RLNE_RLNE") 
TABLESPACE	TS_IAUWEB
;

ALTER TABLE  "FS_AUWEB_US"."US_TUSNE" 
 ADD CONSTRAINT "PK_USNE"
	PRIMARY KEY ("USNE_USNE") 
 USING INDEX
;

CREATE INDEX "PK_USTUSNE"   
 ON  "FS_AUWEB_US"."US_TUSNE" ("USNE_USNE") 
TABLESPACE	TS_IAUWEB
;

/* Create Foreign Key Constraints */

ALTER TABLE  "MO_TROMO" 
 ADD CONSTRAINT "FK_MO_TROMO_MO_TMODU"
	FOREIGN KEY ("MODU_MODU") REFERENCES  "MO_TMODU" ("MODU_MODU")
;

ALTER TABLE  "MO_TROMO" 
 ADD CONSTRAINT "FK_MO_TROMO_US_TRLNE"
	FOREIGN KEY ("RLNE_RLNE") REFERENCES  "US_TRLNE" ("RLNE_RLNE")
;

ALTER TABLE  "US_TPUSR" 
 ADD CONSTRAINT "FK_US_TPUSR_US_TPSNE"
	FOREIGN KEY ("PSNE_PSNE") REFERENCES  "FS_AUWEB_US"."US_TPSNE" ("PSNE_PSNE")
;

ALTER TABLE  "US_TPUSR" 
 ADD CONSTRAINT "FK_US_TPUSR_US_TRLNE"
	FOREIGN KEY ("RLNE_RLNE") REFERENCES  "US_TRLNE" ("RLNE_RLNE")
;

ALTER TABLE  "US_TPUSR" 
 ADD CONSTRAINT "FK_US_TPUSR_US_TUSNE"
	FOREIGN KEY ("USNE_USNE") REFERENCES  "FS_AUWEB_US"."US_TUSNE" ("USNE_USNE")
;
