REM ******************************************************************
REM Fecha         : 08/05/2018
REM Realizado por : Master Zen
REM Base de Datos : FS_AUWEB_US
REM ******************************************************************

REM TABLESPACE Y SEGMENTOS DE ROLLBACK
set feedback off
spool TMP.lst
select distinct 'pause DEBE estar conectado con Usuario SYSTEM' || chr(10) || 'ROLL' || chr(10) || 'EXIT'
from dual
where user <> 'SYSTEM'
/
spool off
start TMP.lst
set feedback on



	DROP TABLE   "FS_AUWEB_US"."MO_TMODU" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_AUWEB_US"."MO_TROMO" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_AUWEB_US"."US_TPSNE" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_AUWEB_US"."US_TPUSR" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_AUWEB_US"."US_TRLNE" CASCADE CONSTRAINTS;



	DROP TABLE   "FS_AUWEB_US"."US_TUSNE" CASCADE CONSTRAINTS;


    
 DROP SEQUENCE "FS_AUWEB_US"."MO_SETMODU";
  DROP SEQUENCE "FS_AUWEB_US"."MO_SETROMO";
   DROP SEQUENCE "FS_AUWEB_US"."US_SETPSNE";
    DROP SEQUENCE "FS_AUWEB_US"."US_SETPUSR";
     DROP SEQUENCE "FS_AUWEB_US"."US_SETRLNE";
      DROP SEQUENCE "FS_AUWEB_US"."US_SETUSNE";
          
          
    
    REM USUARIO  DUENHO DEL APLICATIVO FS_AUWEB_US
drop user FS_AUWEB_US cascade;

REM TABLESPACE DE DATOS
DROP TABLESPACE TS_TAUWEB   INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;
/

REM TABLESPACE DE INDICES 
DROP TABLESPACE TS_AUWEB INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;
/

REM TABLESPACE TEMPORAL
DROP tablespace TS_IAUWEB INCLUDING CONTENTS AND DATAFILES
    CASCADE CONSTRAINTS;
/






